[project]
name = "deepengineer"
version = "0.1.0"
description = "DeepEngineer is a deepsearch project focused on engineering"
readme = "README.md"
authors = [
    { name = "Charles Azam", email = "azamcharles0@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "crawl4ai>=0.6.0",
    "smolagents>=1.19.0",
    "openai",
    "datasets",
    "transformers",
    "litellm",
    "langchain",
    "fasttext-wheel",
    "wikipedia-api",
    "pillow",
    "gradio",
    "python-dotenv>=1.1.1",
    "httpx",
    "pypdf",
    "pytest-asyncio>=1.0.0",
    "mistralai>=1.9.1",
    "fastapi>=0.115.14",
    "supabase>=2.16.0",
]

[project.scripts]
deepengineer = "deepengineer:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
smolagents = { path = "./smolagents", editable = true }

