[pytest]
markers =
    playwright: marks tests that need playwright (deselect with '-m "not playwright"')
    expensive: marks tests that are expensive to run (deselect with '-m "not expensive"')
    asyncio: marks tests that are asyncio (deselect with '-m "not asyncio"')
